### ISSUE TITLE
Enabling chime creates uninterpritable data response

### ISSUE THREAD

**Issue by Webstas** [MattTW/HoneyAlarmServer#18]
Whenever i have chime enabled on my alarm i noticed that alarmserver is sending this response back

Wed, 09 Mar 2016 21:19:55 ERROR <root alarmserver handle_keypad_update> Data for
mat invalid from Envisalink, ignoring...

**Comment by MattTW** [comment]
Hmmm....can you post the "RX <" log message that immediately precedes that message.   Or the last few "RX < ".   That is the raw data received from the Envisalink.

**Comment by Webstas** [comment]
Sat, 12 Mar 2016 21:09:09 DEBUG <root alarmserver lineReceived> RX < %00,01,1C28
,08,00,..WEBSTER-CRIB..CHIME,Rdy to Arm$
Sat, 12 Mar 2016 21:09:09 ERROR <root alarmserver handle_keypad_update> Data for
mat invalid from Envisalink, ignoring...
Sat, 12 Mar 2016 21:09:09 DEBUG <root alarmserver lineReceived> ----------------
------------------------
Sat, 12 Mar 2016 21:09:09 DEBUG <root alarmserver lineReceived> ----------------
------------------------
Sat, 12 Mar 2016 21:09:09 DEBUG <root alarmserver lineReceived> RX < %00,01,1C28
,08,00,..WEBSTER-CRIB..CHIME,Rdy to Arm$
Sat, 12 Mar 2016 21:09:09 ERROR <root alarmserver handle_keypad_update> Data for
mat invalid from Envisalink, ignoring...
Sat, 12 Mar 2016 21:09:09 DEBUG <root alarmserver lineReceived> ----------------
------------------------
Sat, 12 Mar 2016 21:09:18 DEBUG <root alarmserver lineReceived> ----------------
------------------------
Sat, 12 Mar 2016 21:09:18 DEBUG <root alarmserver lineReceived> RX < %00,01,1C28
,08,00,..WEBSTER-CRIB..CHIME,Rdy to Arm$
Sat, 12 Mar 2016 21:09:18 ERROR <root alarmserver handle_keypad_update> Data for
mat invalid from Envisalink, ignoring...
Sat, 12 Mar 2016 21:09:18 DEBUG <root alarmserver lineReceived> ----------------
------------------------
Sat, 12 Mar 2016 21:09:28 DEBUG <root alarmserver lineReceived> ----------------
------------------------
Sat, 12 Mar 2016 21:09:28 DEBUG <root alarmserver lineReceived> RX < %00,01,1C28
,08,00,..WEBSTER-CRIB..CHIME,Rdy to Arm$
Sat, 12 Mar 2016 21:09:28 ERROR <root alarmserver handle_keypad_update> Data for
mat invalid from Envisalink, ignoring...
Sat, 12 Mar 2016 21:09:28 DEBUG <root alarmserver lineReceived> ----------------
------------------------
Sat, 12 Mar 2016 21:09:38 DEBUG <root alarmserver lineReceived> ----------------
------------------------
Sat, 12 Mar 2016 21:09:38 DEBUG <root alarmserver lineReceived> RX < %00,01,1C28
,08,00,..WEBSTER-CRIB..CHIME,Rdy to Arm$
Sat, 12 Mar 2016 21:09:38 ERROR <root alarmserver handle_keypad_update> Data for
mat invalid from Envisalink, ignoring...
Sat, 12 Mar 2016 21:09:38 DEBUG <root alarmserver lineReceived> ----------------
------------------------

**Comment by Webstas** [comment]
wow that formatted weird

**Comment by Webstas** [comment]
now that i think about it, it might be caused  by my naming of the partition and enabling chime might push it over a char limit?

**Comment by MattTW** [comment]
Commas are used as a data separator in the Envisalink communication protocol.   Looks like there is a comma in the last piece of data being sent,  which is the text that is displayed.

Nothing "wrong" with this but it highlights the need to make the code that parses this data a little bit smarter.   I have an idea that I think will work.    Give me a day or two to test it out.

Thanks!
Matt

**Comment by Webstas** [comment]
You're a gentleman and a scholar, thanks for taking a look

**Comment by MattTW** [comment]
sorry about the long delay - I pushed a fix up that should correct that error - give it a try when you have a chance.

**Comment by Webstas** [comment]
Awesome i will give it a try

**Comment by Webstas** [comment]
i updated to the latest code set but im still getting that issue with chime, also now im getting empty partition responses 

`Tue, 17 May 2016 10:38:38 DEBUG <requests.packages.urllib3.connectionpool conne
tionpool _make_request> "GET /api/smartapps/installations/e289c007-4b1b-4d40-b2
9-b4036fe7f126/panel/610/53?access_token=c8d3a768-79f2-4722-90b2-5f95d6bc7b44 H
TP/1.1" 200 0
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> RX < %00,01,000
,21,00,FAULT 21 KITCHENSIDE WINDOW     $
Tue, 17 May 2016 10:38:38 DEBUG <root smartthings partitionStatus> Partition or
status was empty, skipping this event. NOTE: This may be an error, if so we nee
 to get a proper status for whatever even this is to fix it
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> RX < %00,01,000
,22,00,FAULT 22        MAW(N)PAW WINDOW$
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> RX < %00,01,000
,21,00,FAULT 21 KITCHENSIDE WINDOW     $
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> RX < %00,01,000
,22,00,FAULT 22        MAW(N)PAW WINDOW$
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> RX < %00,01,000
,21,00,FAULT 21 KITCHENSIDE WINDOW     $
Tue, 17 May 2016 10:38:38 DEBUG <root alarmserver lineReceived> ---------------
------------------------
`
